const allConcepts = {
    "Cognitive Dissonance": "The mental discomfort experienced when a person holds two or more contradictory beliefs, values, or attitudes. This theory, developed by Leon Festinger, suggests that people are motivated to reduce this dissonance by changing their attitudes, beliefs, or behaviors.",
    "Classical Conditioning": "A learning process that occurs when two stimuli are repeatedly paired. A response initially elicited by the second stimulus is eventually elicited by the first stimulus alone. Pavlov's experiments with dogs are a well-known example.",
    "Operant Conditioning": "A method of learning that occurs through rewards and punishments for behavior. Through operant conditioning, an association is made between a behavior and a consequence (Skinner).",
    "Attachment Theory": "A psychological model that describes the dynamics of long-term interpersonal relationships between humans. Developed by John Bowlby, the theory emphasizes the importance of a secure and trusting bond between a child and their caregiver.",
    "Behaviorism": "A systematic approach to understanding the behavior of humans and other animals. It assumes that all behaviors are either reflexes produced by a response to certain stimuli or a consequence of the individual's history, including especially reinforcement and punishment (Watson and Skinner).",
    "Social Learning Theory": "The theory that people can learn through observation and imitation of others. Albert Bandura's Bobo doll experiment demonstrated that children could learn aggressive behaviors by watching others.",
    "Psychoanalysis": "A set of psychological theories and therapeutic techniques that have their origin in the work and theories of Sigmund Freud. The primary assumption is that the unconscious mind governs behavior to a greater degree than people suspect.",
    "Hierarchy of Needs": "A theory of human motivation proposed by Abraham Maslow in 1943. It suggests that people are motivated to fulfill basic needs before moving on to other, more advanced needs, culminating in self-actualization.",
    "Positive Reinforcement": "The addition of a rewarding stimulus following a desired behavior with the aim of increasing the likelihood of the behavior being repeated.",
    "Negative Reinforcement": "The removal of an aversive stimulus following a desired behavior with the aim of increasing the likelihood of the behavior being repeated.",
    "Cognitive Development": "A field of study in neuroscience and psychology focusing on a child's development in terms of information processing, conceptual resources, perceptual skill, language learning, and other aspects of brain development. Jean Piaget's stages of cognitive development are key in this field.",
    "Self-Efficacy": "An individual's belief in their own ability to succeed in specific situations or accomplish a task. This concept was introduced by Albert Bandura.",
    "Unconscious Mind": "The part of the mind that is inaccessible to the conscious mind but that affects behavior and emotions. Freud's theory of the unconscious includes repressed feelings, memories, and desires.",
    "Defense Mechanisms": "Psychological strategies brought into play by various entities to cope with reality and to maintain self-image. Examples include repression, denial, and projection.",
    "Neuroplasticity": "The ability of the brain to change continuously throughout an individual's life, enabling it to reorganize itself by forming new neural connections.",
    "Intrinsic Motivation": "Performing an action or behavior because you enjoy the activity itself, rather than relying on external rewards or pressures.",
    "Extrinsic Motivation": "Behavior that is driven by external rewards such as money, fame, grades, and praise.",
    "Learned Helplessness": "A mental state in which an individual who has experienced repeated aversive stimuli feels unable to avoid or escape from subsequent similar situations, often leading to passive resignation and depression.",
    "Conditioned Response": "In classical conditioning, the learned response to a previously neutral stimulus that has become associated with an unconditioned stimulus.",
    "Id, Ego, and Superego": "The three parts of the psychic apparatus defined in Sigmund Freud's structural model of the psyche. The id is the set of uncoordinated instinctual desires; the super-ego plays the critical and moralizing role; and the ego is the organized, realistic part that mediates between the desires of the id and the super-ego.",
    "Self-Actualization": "The realization or fulfillment of one's talents and potentialities, considered as a drive or need present in everyone. This concept is at the top of Maslow's hierarchy of needs.",
    "Humanistic Psychology": "A psychological perspective that emphasizes the study of the whole person and the uniqueness of each individual. Humanistic psychologists look at human behavior not only through the eyes of the observer, but through the eyes of the person doing the behaving.",
    "Schemas": "Cognitive frameworks or concepts that help individuals organize and interpret information. Schemas can be useful because they allow us to take shortcuts in interpreting the vast amount of information that is available in our environment.",
    "Zone of Proximal Development": "The range of tasks that a child can perform with the help and guidance of others but cannot yet perform independently, a concept developed by Lev Vygotsky.",
    "Social Facilitation": "The tendency for people to perform differently when in the presence of others than when alone. Specifically, individuals perform better on simple or well-rehearsed tasks and worse on complex or new ones.",
    "Cognitive Behavioral Therapy (CBT)": "A psycho-social intervention that aims to improve mental health. CBT focuses on challenging and changing unhelpful cognitive distortions and behaviors, improving emotional regulation, and the development of personal coping strategies.",
    "Mirror Neurons": "Neurons that fire both when an individual performs an action and when they observe the same action performed by another. They are believed to play a role in understanding others' actions, learning through imitation, and the development of empathy.",
    "Groupthink": "A psychological phenomenon that occurs within a group of people in which the desire for harmony or conformity results in an irrational or dysfunctional decision-making outcome.",
    "Confirmation Bias": "The tendency to search for, interpret, favor, and recall information in a way that confirms one's preexisting beliefs or hypotheses.",
    "Implicit Bias": "The attitudes or stereotypes that affect our understanding, actions, and decisions in an unconscious manner.",
    "Emotional Intelligence": "The capability of individuals to recognize their own emotions and those of others, discern between different feelings and label them appropriately, use emotional information to guide thinking and behavior, and manage and/or adjust emotions to adapt to environments or achieve one's goals.",
    "Fixed vs. Growth Mindset": "Carol Dweck's theory that individuals can have either a fixed mindset, where they believe their abilities are static, or a growth mindset, where they believe their abilities can be developed through dedication and hard work.",
    "Heuristics": "Mental shortcuts or 'rules of thumb' that often lead to a solution (but not always).",
    "Affect Heuristic": "A type of mental shortcut in which people make decisions that are heavily influenced by their current emotions.",
    "Flow": "The mental state in which a person performing an activity is fully immersed in a feeling of energized focus, full involvement, and enjoyment in the process of the activity.",
    "Attribution Theory": "The process by which individuals explain the causes of behavior and events. Attribution theory is a framework for understanding how people explain others' behavior and their own.",
    "Fundamental Attribution Error": "The tendency for people to overemphasize personality-based explanations for behaviors observed in others while underemphasizing situational explanations.",
    "Cognitive Bias": "A systematic pattern of deviation from norm or rationality in judgment, whereby inferences about other people and situations may be drawn in an illogical fashion.",
    "Priming": "The exposure to one stimulus influences a response to a subsequent stimulus, without conscious guidance or intention.",
    "Self-Fulfilling Prophecy": "A prediction that causes itself to become true due to the behavior of the believer.",
    "Maslow’s Hierarchy of Needs": "A motivational theory in psychology comprising a five-tier model of human needs, often depicted as hierarchical levels within a pyramid.",
    "Vicarious Reinforcement": "Learning that occurs by observing the reinforcement or punishment of another person.",
    "Gestalt Psychology": "A psychological approach that emphasizes that we often perceive the whole rather than the sum of the parts.",
    "Anchoring Bias": "The common human tendency to rely too heavily on the first piece of information offered (the 'anchor') when making decisions.",
    "Conformity": "The act of matching attitudes, beliefs, and behaviors to group norms or politics.",
    "Deindividuation": "A concept in social psychology that is generally thought of as the loss of self-awareness in groups, although this is a matter of contention.",
    "In-group Bias": "The tendency to favor one's own group over other groups.",
    "Obedience to Authority": "A form of social influence where an individual acts in response to a direct order from another individual, who is usually an authority figure.",
    "Just-world Hypothesis": "The cognitive bias that a person's actions are inherently inclined to bring morally fair and fitting consequences to that person.",
    "Prosocial Behavior": "Positive, helping behavior intended to promote social acceptance and friendship."
};

export default allConcepts;